<?php

use app\core\traits\Reservations;

$reservations  = $this->get_all_reservations();
$lanes         = $this->lanes->get_all_lanes();
$menus         = $this->menus->get_all_menus();
$menus_numbers = Reservations::get_all_menus_numbers( $menus );

?>

<div id="stage-table-wrapper">
    <div class="users">
        <span class="table-row">
            <span class="table-header">Baan</span>
            <span class="table-header">Menu</span>
            <span class="table-header">Glow in the dark</span>
            <span class="table-header">Personen</span>
            <span class="table-header">Klant</span>
            <span class="table-header">Datum</span>
            <span class="table-header">Time</span>
            <span class="table-header">Since</span>
            <span class="table-header">Delete</span>
        </span>
        <?php foreach( $reservations as $reservation ): ?>
            <?php $customer = $this->get_reservation_customer( $reservation->id ); ?>
            <form action="<?= BASE_PATH ?>reservations/edit" method="post" class="table-row">
                <input type="hidden" name="reservation_id" value="<?= $reservation->id ?>">
                <span class="table-cell">
                    <select name="lane" id="updateUser">
                        <option value="<?= $reservation->lane_id ?>"><?= Reservations::convert_lane_id( $reservation->lane_id, $lanes ) ?></option>
                        <?php foreach( $lanes as $lane ): ?>
                            <?php if( $reservation->lane_id !== $lane->id ): ?>
                                <option value="<?= $lane->id ?>"><?= $lane->lane ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </span>
                <span class="table-cell">
                     <select name="menu" id="updateUser">
                         <option value="<?= $reservation->menu ?>"><?= $reservation->menu ?></option>
                        <?php foreach( $menus_numbers as $menus_number => $data ): ?>
                            <?php if( $reservation->menu !== $data['menu'] ): ?>
                                <option value="<?= $data['menu'] ?>"><?= $data['menu'] ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </span>
                <span class="table-cell-radio">
                    Ja <input type="radio" id="updateUser" name="glow_in_dark" value="yes" <?= $reservation->glow_in_dark === "yes" ? "checked=checked" : "" ?>>
                    Nee <input type="radio" id="updateUser" name="glow_in_dark" value="no" <?= $reservation->glow_in_dark === "no" ? "checked=checked" : "" ?>>
                </span>
                <span class="table-cell"><input type="text" id="updateUser" name="persons" value="<?= $reservation->persons ?>"></span>
                <span class="table-cell">
                    <?php
                        if( !empty( $customer ) ):
                            echo $customer->name;
                            echo '<br>'.$customer->email;
                            echo '<br>'.$customer->phone;
                        else:
                            echo 'Geen data beschikbaar';
                        endif;
                    ?>
                </span>
                <span class="table-cell"><input id="updateUser" type="date" name="reservation" value="<?= $reservation->reservation ?>"></span>
                <span class="table-cell"><input id="updateUser" type="time" name="time" value="<?= $reservation->time ?>"></span>
                <span class="table-cell"><?= $reservation->created_at ?></span>
                <span class="table-cell-delete">
                    <a id="deleteUser" class="users-delete" data-url="<?= BASE_PATH ?>reservations/delete/<?= $reservation->id ?>" title="Delete this reservation"></a>
                </span>
            </form>
        <?php endforeach; ?>
    </div>
</div>