<div class="container">
    <div class="container-title">Nieuw personeelslid toevoegen</div>
</div>


<div class="container-centered">

    <form action="<?= BASE_PATH ?>staff/add_staff" method="post">
        <fieldset>
            <legend>Vul onderstaande gegevens in</legend>
            <p>
                Zodra een toegevoegd personeelslid inlogt wordt hij/zij verzocht om een wachtwoord op te geven.
            </p>
            <input type="text" name="first_name" value="" placeholder=" Voornaam">
            <input type="text" name="insertion" value="" placeholder=" Tussenvoegsel">
            <input type="text" name="last_name" value="" placeholder=" Achternaam">
            <input type="email" name="email" value="" placeholder=" Email">

            <input type="submit" name="newStaffSubmit" value="toevoegen">
        </fieldset>
    </form>

</div>