<?php

use app\core\Library as Lib;

$user_types  = $this->user_types_array();
$random_pass = Lib::random_password();
?>

<div class="container">
    <div class="container-title">Add user</div>
</div>

<div class="new-user">
    <form action="<?= BASE_PATH ?>users/add_user" method="post">
        <fieldset>
            <legend>Enter an email and type</legend>
            <input type="email" name="email" value="" placeholder="Email">
            <select name="type">
                <option value="">Choose a type</option>
                <?php foreach( $user_types as $user_type ): ?>
                <option value="<?= $user_type ?>"><?= $user_type ?></option>
                <?php endforeach; ?>
            </select>
            <div class="random">Temporary password: <?= $random_pass ?></div>
            <input type="hidden" name="password" value="<?= $random_pass ?>">
            <input type="submit" name="newUserSubmit" value="Add">
        </fieldset>
    </form>
</div>
