<div class="container">
    <div class="container-title">Login</div>
    <div class="login">
        <form action="<?= BASE_PATH ?>login/authorize" method="post">
            <fieldset>
                <legend>Please fill in your email and password</legend>
                <input type="email" name="email" value="" placeholder="Email" title="Fill in your email">
                <input type="password" name="password" value="" placeholder="Password" title="Fill in your password">
                <input type="submit" name="login_submit" value="Login" title="Click to login">
            </fieldset>
        </form>
    </div>
</div>