<div class="container">
    <div class="container-title">Home</div>
</div>

<div class="blockContainer">

    <div class="block60 darkGrayBlock blockFont110 blockColorWhite">
        Blueberry is actuariele middleware voor math en data financiers.
    </div>

    <div class="block60 lightGrayBlock blockFont100">
        <div class="blockImage4">
            <img src="<?= BASE_PATH ?>img/icons/middleware.png" title="The Process">
            <span>The process</span>
        </div>

        <div class="blockImage4">
            <img src="<?= BASE_PATH ?>img/icons/project_icon.png" title="The project">
            <span>Project</span>
        </div>

        <div class="blockImage4">
            <img src="<?= BASE_PATH ?>img/icons/model_icon.png" title="The model">
            <span>Model</span>
        </div>

        <div class="blockImage4">
            <img src="<?= BASE_PATH ?>img/icons/calculator_icon.png" title="The calculator">
            <span>Calculator</span>
        </div>
    </div>

    <div class="block60 lightGrayBlock blockFont100">
        <h2>Momenteel ondersteunen wij de volgende bestandstypen:</h2>
            <div class="excelImage">
                <img src="<?= BASE_PATH ?>img/icons/excel_logo.png" title="The calculator">
                <span>.XLSX</span>
            </div>
            <div class="eaImage">
                <img src="<?= BASE_PATH ?>img/icons/ea_logo.gif" title="The calculator">
                <span>.XML</span>
            </div>
    </div>

</div>