<?php

use app\core\traits\Reservations;

$lanes        = $this->lanes->get_all_lanes();
$menus        = $this->menus->get_all_menus();
$menu_numbers = Reservations::get_all_menus_numbers( $menus );

?>

<div class="container">
    <div class="container-icon"><img src="<?= PUBLIC_PATH ?>img/icons/reservation_icon2.png"></div>
    <div class="container-title">Nieuwe reservering toevoegen</div>
</div>


<div class="container-centered">

    <form action="<?= BASE_PATH ?>reservations/add" method="post">
        <fieldset>
            <legend>Vul onderstaande gegevens in</legend>
            <select name="lane">
                <option value="">Kies een baan</option>
                <?php foreach( $lanes as $lane ): ?>
                    <option value="<?= $lane->id ?>"><?= $lane->lane ?></option>
                <?php endforeach; ?>
            </select>
            <br><br>
            <select name="menu">
                <option value="">Kies een menu</option>
                <?php foreach( $menu_numbers as $menu_number => $data ): ?>
                    <option value="<?= $data['id'] ?>"><?= $data['menu'] ?></option>
                <?php endforeach; ?>
            </select>
            <br><br>
            <span>
                Glow in the dark?
            </span>
            Ja <input type="radio" name="glow_in_dark" value="yes">
            Nee <input type="radio" name="glow_in_dark" value="no">
            <br><br>
            Datum <input type="date" name="reservation" value="">
            Tijd <input type="time" name="time" value="">

            <input type="text" name="name" value="" placeholder="Volledige naam">
            <input type="text" name="phone" value="" placeholder="Telefoon">
            <input type="text" name="email" value="" placeholder="Email">
            <input type="text" name="persons" value="" placeholder="Personen">

            <input type="submit" name="newReservationSubmit" value="toevoegen">
        </fieldset>
    </form>

</div>