<?php $reservations = $this->get_all_reservations(); ?>

<div id="stage-table-wrapper">
    <div class="users">
        <span class="table-row">
            <span class="table-header">Lane</span>
            <span class="table-header">Menu</span>
            <span class="table-header">Datum</span>
            <span class="table-header">Updated at</span>
            <span class="table-header">Delete</span>
        </span>
        <?php foreach( $reservations as $reservation ): ?>
            <form action="<?= BASE_PATH ?>reservation/edit" method="post" class="table-row">
                <input type="hidden" name="reservation_id" value="<?= $reservation->id ?>">
                <span class="table-cell"><input id="updateUser" type="text" name="first_name" value="<?= $reservation->lane_id ?>"></span>
                <span class="table-cell"><input id="updateUser" type="text" name="insertion" value="<?= $reservation->menu ?>"></span>
                <span class="table-cell"><input id="updateUser" type="text" name="last_name" value="<?= $reservation->reservation ?>"></span>
                <span class="table-cell"><?= $reservation->created_at ?></span>
                <span class="table-cell-delete">
                    <a id="deleteUser" class="users-delete" data-url="<?= BASE_PATH ?>reservation/delete/<?= $reservation->id ?>" title="Delete this reservation"></a>
                </span>
            </form>
        <?php endforeach; ?>
    </div>
</div>