<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="">
    <meta name="robots" content="nofollow">
    <meta property="og:title" content="Control Management System">
    <meta property="og:type" content="website">
    <meta property="og:description" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Raleway%7cPassion+One%7cWork+Sans%7cRoboto+Condensed:400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="<?= CSS_PATH ?>">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <title>Wacka Wally Bowling Alley</title>
</head>
<body>
<div class="se-pre-con">
    <div class="se-pre-con-txt">
            <span>
                <img src="<?= PUBLIC_PATH . 'img/icons/gears.gif?'. uniqid() ?>">
                <br>
                Loading, please wait...
            </span>
    </div>
</div>

<div class="header">
    <?php
    /**
     * Only show menu when logged in
     */
        if( !empty( $_SESSION['login'] ) ):
    ?>
        <div class="header-navigation dropdown">

            <button onclick="menuDropDown()" class="dropbtn"></button>

            <div id="myDropdown" class="dropdown-content">

                <a href="<?= BASE_PATH ?>home/index">Home</a>

                <?php
                /**
                 * Only show users option if user is admin or superuser
                 */
                    if( $this->is_admin_or_super_user() ):
                ?>
                    <a href="<?= BASE_PATH ?>users/index">Users</a>
                <?php
                    endif;
                ?>

                <a href="<?= BASE_PATH ?>personeel/index">Personeel</a>
                <a href="<?= BASE_PATH ?>banen/index">Banen</a>
                <a href="<?= BASE_PATH ?>menu/index">Menu</a>
                <a href="<?= BASE_PATH ?>reserveringen/index">Reserveringen</a>
                <a href="<?= BASE_PATH ?>contact/index">Contact</a>

            </div>
        </div>
    <?php endif; ?>

        <div class="header-title">Wacka Wally Bowling Alley</div>

        <?php if( !empty( $_SESSION['login'] ) ): ?>
            <div class="header-logout">
                <img class="logout-img" data-alt-src="<?= PUBLIC_PATH . 'img/icons/lock_icon_closed.png'?>" src="<?= PUBLIC_PATH ?>img/icons/lock_icon_open.png">
                <a class="logout" href="<?= BASE_PATH ?>login/logout" title="Click to logout">Logout</a>
            </div>
        <?php endif; ?>
</div>