<?php

use app\core\Library as Lib;

$random_pass = Lib::random_password();
$user_types  = $this->user_types_array();

?>

<div class="container">
    <div class="container-icon"><img src="<?= PUBLIC_PATH ?>img/icons/add_staff_icon.png"></div>
    <div class="container-title">Nieuw personeelslid toevoegen</div>
</div>


<div class="container-centered">

    <form action="<?= BASE_PATH ?>staff/add_staff" method="post">
        <fieldset>
            <legend>Vul onderstaande gegevens in</legend>
            <p>
                Sla het tijdelijke wachtwoord op!
            </p>
            <input type="text" name="first_name" value="" placeholder=" Voornaam">
            <input type="text" name="insertion" value="" placeholder=" Tussenvoegsel">
            <input type="text" name="last_name" value="" placeholder=" Achternaam">
            <input type="email" name="email" value="" placeholder=" Email">
            <select name="type">
                <option value="">Kies een type</option>
                <?php foreach( $user_types as $user_type ): ?>
                    <option value="<?= $this->convert_user_type_number( $user_type ) ?>"><?= $user_type ?></option>
                <?php endforeach; ?>
            </select>
            <br><br>
            <p>
                Tijdelijk wachtwoord: <?= $random_pass ?>
            </p>
            <input type="hidden" name="password" value="<?= $random_pass ?>" placeholder=" Email">

            <input type="submit" name="newStaffSubmit" value="toevoegen">
        </fieldset>
    </form>

</div>